const categories = {
    "个人信息": [
        { "question": "身高", "answer": "" },
        { "question": "年级", "answer": "" },
        { "question": "血型", "answer": "" },
        { "question": "生日", "answer": "" },
        { "question": "长发/短发?", "answer": "" },
        { "question": "住在哪个城市", "answer": "" },
        { "question": "一次元/二次元/三次元?", "answer": "" },
        { "question": "有没有兄弟姐妹?", "answer": "" },
        { "question": "你的星座是什么?", "answer": "" },
        { "question": "是否养宠物?", "answer": "" }
    ],
    "生活习惯": [
        { "question": "一般几点睡几点起?", "answer": "" },
        { "question": "怕热/怕冷?", "answer": "" },
        { "question": "MBTI", "answer": "" },
        { "question": "早上和晚上更喜欢哪个时段?", "answer": "" },
        { "question": "用三个词形容一下自己的性格", "answer": "" },
        { "question": "给哪个游戏氪的金最多", "answer": "" },
        { "question": "有没有经历过灵异事件", "answer": "" },
        { "question": "日常最依赖的电子设备是什么?", "answer": "" },
        { "question": "工作时更倾向于听音乐还是安静环境?", "answer": "" }
    ],
    "兴趣爱好": [
        { "question": "说一个自己的特长/兴趣爱好", "answer": "" },
        { "question": "最想获得什么超能力", "answer": "" },
        { "question": "坚持了很久的习惯/爱好/没有倒的flag", "answer": "" },
        { "question": "特别的癖好或习惯", "answer": "" },
        { "question": "喜欢的颜色", "answer": "" },
        { "question": "喜欢的食物", "answer": "" },
        { "question": "喜欢的音乐风格", "answer": "" },
        { "question": "最喜欢的运动", "answer": "" },
        { "question": "最近最喜欢的一首歌/音乐", "answer": "" },
        { "question": "最喜欢的书籍/番剧/电影是什么?", "answer": "" },
        { "question": "喜欢的奶茶配料", "answer": "" },
        { "question": "喜欢的月饼口味", "answer": "" },
        { "question": "最喜欢的薯片口味", "answer": "" },
        { "question": "最喜欢/最讨厌的水果", "answer": "" },
        { "question": "最喜欢的季节", "answer": "" },
        { "question": "最喜欢的动物", "answer": "" },
        { "question": "最喜欢的一句话/座右铭", "answer": "" },
        { "question": "最喜欢的诗人", "answer": "" },
        { "question": "最喜欢的一天之中的什么时候", "answer": "" },
        { "question": "喜欢什么设定的小说", "answer": "" },
        { "question": "喜欢看破镜重圆的文吗", "answer": "" },
        { "question": "喜欢一见钟情OR日久深情", "answer": "" },
        { "question": "喜欢磕的CP在哪里DO", "answer": "" },
        { "question": "喜欢开着空调盖被子吗", "answer": "" },
        { "question": "喜欢裙子喜欢长裙OR短裙", "answer": "" },
        { "question": "喜欢喜欢磕的圈子", "answer": "" },
        { "question": "喜欢磕过最冷门的圈子", "answer": "" },
        { "question": "喜欢看文喜欢年上OR年下", "answer": "" }
    ],
    "情感与价值观": [
        { "question": "最害怕的事物是什么?", "answer": "" },
        { "question": "最近一次emo的原因", "answer": "" },
        { "question": "讨厌什么样的人", "answer": "" },
        { "question": "说说讨厌的事物", "answer": "" },
        { "question": "你最看重朋友的哪些特质?", "answer": "" },
        { "question": "你认为爱情的本质是什么?", "answer": "" },
        { "question": "人生中最遗憾的一件事是什么?", "answer": "" },
        { "question": "如果明天就是世界末日你今天会做什么?", "answer": "" },
        { "question": "是否相信来生/天堂/灵魂?", "answer": "" },
        { "question": "谈谈对金钱和成功的看法", "answer": "" },
        { "question": "会因为什么和一个人做朋友", "answer": "" },
        { "question": "说说自己的xp", "answer": "" }
    ],
    "回忆与成长": [
        { "question": "过去的人生中最骄傲的事", "answer": "" },
        { "question": "感到最幸运的事", "answer": "" },
        { "question": "谈谈最怀念的一段时光", "answer": "" },
        { "question": "小时候最喜欢玩的游戏是什么?", "answer": "" },
        { "question": "三年前的自己和现在最大的区别是什么?", "answer": "" },
        { "question": "最想回到过去的哪个时候?", "answer": "" },
        { "question": "一个让你觉得温暖或感动的瞬间", "answer": "" },
        { "question": "你认为自己的成长动力是什么?", "answer": "" },
        { "question": "如果你的人生是一本书，会起什么名字?", "answer": "" },
        { "question": "说说去年最开心的三件事", "answer": "" },
        { "question": "做过什么奇怪的梦", "answer": "" },
        { "question": "想对三年前的自己说什么", "answer": "" },
        { "question": "吐槽一件最近遇到的糟心事", "answer": "" },
        { "question": "最早混的圈是什么", "answer": "" },
        { "question": "最近刚喜欢上的推是谁", "answer": "" }
    ],
    "推荐与分享": [
        { "question": "推荐一个冷门但好用的APP", "answer": "" },
        { "question": "推荐一个文手/画手", "answer": "" },
        { "question": "推荐一个up主/微博大v", "answer": "" },
        { "question": "推荐一个tb店", "answer": "" },
        { "question": "推荐一款零食", "answer": "" },
        { "question": "推荐一款奶茶配方", "answer": "" },
        { "question": "推荐一个游戏", "answer": "" },
        { "question": "推荐一个作者", "answer": "" },
        { "question": "推荐一个捏脸", "answer": "" },
        { "question": "推荐一个生活好物/食谱/生活小窍门", "answer": "" },
        { "question": "最近使用的五个emoji", "answer": "" },
        { "question": "剪贴板最后复制的东西", "answer": "" },
        { "question": "听音乐用哪个软件", "answer": "" }
    ],
    "情感与关系": [
        { "question": "喜欢一见钟情OR日久深情", "answer": "" },
        { "question": "觉得自己谈恋爱是主动型的吗", "answer": "" },
        { "question": "是否单身", "answer": "" },
        { "question": "谈过几段恋爱", "answer": "" },
        { "question": "有无心选", "answer": "" },
        { "question": "非单谈谈自己的对象/单身狗谈谈自己的理想型", "answer": "" },
        { "question": "最想拥有的超能力", "answer": "" },
        { "question": "另一半理想身高", "answer": "" }
    ],
    "兴趣拓展": [
        { "question": "喜欢什么设定的小说", "answer": "" },
        { "question": "看小说喜欢天降OR竹马", "answer": "" },
        { "question": "推荐一部番", "answer": "" },
        { "question": "推荐一本小说", "answer": "" },
        { "question": "推一本自己喜欢的冷门小说", "answer": "" },
        { "question": "有没有现在还喜欢的动画", "answer": "" },
        { "question": "喜欢什么样的电影", "answer": "" },
        { "question": "喜欢什么样的花", "answer": "" },
        { "question": "喜欢的地方", "answer": "" },
        { "question": "喜欢的电影", "answer": "" },
        { "question": "推荐一部下饭综艺", "answer": "" },
        { "question": "看电影看到感动的地方会哭吗", "answer": "" }
    ],
    "日常与偏好": [
        { "question": "喜欢还是讨厌香菜", "answer": "" },
        { "question": "喜欢清淡还是重口味", "answer": "" },
        { "question": "最喜欢的食物", "answer": "" },
        { "question": "最喜欢的水果", "answer": "" },
        { "question": "喜欢什么奶茶", "answer": "" },
        { "question": "喜欢什么颜色", "answer": "" },
        { "question": "喜欢什么味道的沐浴露", "answer": "" },
        { "question": "喜欢什么颜色的衣服最多", "answer": "" },
        { "question": "喜欢裙子喜欢长裙OR短裙", "answer": "" },
        { "question": "喜欢什么口味的冰淇淋", "answer": "" },
        { "question": "喜欢磕的CP在哪里DO", "answer": "" },
        { "question": "喜欢开着空调盖被子吗", "answer": "" }
    ],
    "其他": [
        { "question": "坚持最久的一件事", "answer": "" },
        { "question": "追星吗 为什么喜欢她/他", "answer": "" },
        { "question": "以后想过什么样的生活", "answer": "" },
        { "question": "推荐一首最近循环听的歌", "answer": "" },
        { "question": "磕过最冷门的圈子", "answer": "" },
        { "question": "有可能的话想回到几岁", "answer": "" },
        { "question": "做过现在想都觉得很傻的事吗", "answer": "" },
        { "question": "觉得自由是什么味道的", "answer": "" },
        { "question": "不开心的时候喜欢做什么", "answer": "" },
        { "question": "推荐一份小零食", "answer": "" },
        { "question": "用一种颜色形容喜欢的季节", "answer": "" },
        { "question": "理想的学校", "answer": "" },
        { "question": "有最难忘的事吗", "answer": "" },
        { "question": "推荐一个你去过的地方", "answer": "" },
        { "question": "最近让你印象深刻的事情", "answer": "" },
        { "question": "最喜欢的天气", "answer": "" },
        { "question": "以后想养只什么小动物", "answer": "" },
        { "question": "看的第一本的小说", "answer": "" },
        { "question": "三次留着什么样的发型", "answer": "" },
        { "question": "疫情前去过最怀念的地方", "answer": "" },
        { "question": "最近吃的谷是什么", "answer": "" },
        { "question": "小时候的梦想", "answer": "" },
        { "question": "有没有什么特长", "answer": "" },
        { "question": "你吃饭时的电子榨菜是什么", "answer": "" },
        { "question": "最擅长的科目", "answer": "" },
        { "question": "看文能接受的年龄差", "answer": "" },
        { "question": "异性哪一瞬间让你心动", "answer": "" },
        { "question": "用有线耳机还是蓝牙耳机", "answer": "" },
        { "question": "炒饭OR炒面OR炒粉", "answer": "" },
        { "question": "有短暂的目标吗", "answer": "" },
        { "question": "睡觉前喜欢做什么", "answer": "" },
        { "question": "有没有什么隐藏特长", "answer": "" },
        { "question": "最喜欢的发色", "answer": "" },
        { "question": "有无心选", "answer": "" },
        { "question": "推荐的番剧", "answer": "" },
        { "question": "推荐的小说", "answer": "" },
        { "question": "推荐的动画", "answer": "" },
        { "question": "推荐的游戏", "answer": "" },
        { "question": "推荐的电影", "answer": "" },
        { "question": "推荐的音乐", "answer": "" },
        { "question": "推荐的书籍", "answer": "" },
        { "question": "推荐的诗歌", "answer": "" },
        { "question": "推荐的歌词", "answer": "" },
        { "question": "推荐的零食", "answer": "" },
        { "question": "推荐的饮料", "answer": "" },
        { "question": "推荐的服饰", "answer": "" },
        { "question": "推荐的护肤品", "answer": "" },
        { "question": "推荐的旅行地点", "answer": "" },
        { "question": "推荐的餐厅", "answer": "" },
        { "question": "推荐的咖啡店", "answer": "" },
        { "question": "推荐的书店", "answer": "" },
        { "question": "推荐的电影院", "answer": "" },
        { "question": "推荐的运动方式", "answer": "" }
    ]
}